import type { Metadata } from "next";
import { LegalShell, MerchantAddress } from "@/components/legal-shell";
import { storeConfig } from "@/lib/config";

export const metadata: Metadata = { title: "Datenschutzerklärung" };
export default function PrivacyPage() {
  const m = storeConfig.merchant;
  return <LegalShell eyebrow="DSGVO + TDDDG" title="Datenschutz" intro="Wie personenbezogene Daten in Storefront, Checkout und Kommunikation verarbeitet werden.">
    <section><h2>1. Verantwortlicher</h2><MerchantAddress /><p>E-Mail: <a href={`mailto:${m.email}`}>{m.email}</a><br />Telefon: {m.phone}</p></section>
    <section><h2>2. Aufruf dieser Website</h2><p>Beim Aufruf verarbeitet der Hosting-Anbieter technisch erforderliche Verbindungsdaten wie IP-Adresse, Zeitpunkt, angeforderte Ressource, Referrer sowie Browser- und Betriebssystemangaben. Die Verarbeitung dient dem sicheren, stabilen Betrieb gemäß Art. 6 Abs. 1 lit. f DSGVO. Serverprotokolle sind auf eine angemessene, konkret festzulegende Dauer zu begrenzen.</p></section>
    <section><h2>3. Hosting durch Vercel</h2><p>Die Storefront wird über Vercel bereitgestellt. Dabei können Daten in Drittländern verarbeitet werden. Vor Go-live sind Auftragsverarbeitungsvertrag, konkrete Region, Transfermechanismen, Unterauftragsverarbeiter und Löschfristen anhand des aktuellen Vercel-Vertragsstands zu dokumentieren.</p></section>
    <section><h2>4. Shopify, Warenkorb und Bestellung</h2><p>Produkte und Checkout werden über Shopify bereitgestellt. Bei Öffnung des Shopify Checkouts verarbeitet Shopify die für Vertrag, Zahlung, Betrugsprävention, Steuer und Lieferung erforderlichen Daten. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b und c DSGVO sowie bei Sicherheitsmaßnahmen Art. 6 Abs. 1 lit. f DSGVO. Die Shopify-Datenschutzeinstellungen, der Auftragsverarbeitungsnachtrag und die Verbraucher-Datenschutzerklärung von Shopify müssen vor Go-live mit den aktivierten Funktionen abgeglichen werden.</p></section>
    <section><h2>5. Lokaler Warenkorb</h2><p>Der Warenkorb wird bis zur Übergabe an Shopify lokal im Browser gespeichert. Das ist erforderlich, um den ausdrücklich angeforderten Warenkorbdienst bereitzustellen (§ 25 Abs. 2 Nr. 2 TDDDG). Die Daten verlassen das Gerät erst beim Checkout und können durch Leeren des Warenkorbs oder der Browserdaten gelöscht werden.</p></section>
    <section><h2>6. Cookies und Einwilligung</h2><p>Notwendige Speicherungen sichern Warenkorb, Sicherheit und die Consent-Auswahl. Nicht notwendige Analyse-, Marketing- oder Personalisierungstechnologien werden erst nach Einwilligung nach § 25 Abs. 1 TDDDG in Verbindung mit Art. 6 Abs. 1 lit. a DSGVO aktiviert. Eine Einwilligung kann jederzeit über „Cookie-Einstellungen“ im Footer mit Wirkung für die Zukunft geändert werden.</p></section>
    <section><h2>7. Kontakt und elektronischer Widerruf</h2><p>Kontakt- und Widerrufsdaten werden zur Bearbeitung der Anfrage beziehungsweise Vertragsabwicklung verarbeitet (Art. 6 Abs. 1 lit. b DSGVO), gesetzlich erforderliche Nachweise nach Art. 6 Abs. 1 lit. c DSGVO. Der E-Mail-Versand erfolgt nach Konfiguration über Resend. Empfänger, Region, Vertragsunterlagen und Löschfristen sind vor Go-live verbindlich festzulegen.</p></section>
    <section><h2>8. Zahlungen, Versand und digitale Bereitstellung</h2><p>Je nach aktivierter Shopify-Konfiguration erhalten Zahlungsdienstleister, Versandunternehmen sowie eine App zur Bereitstellung digitaler Downloads die erforderlichen Daten. Vor Veröffentlichung sind hier alle tatsächlich eingesetzten Anbieter, Zwecke, Rechtsgrundlagen, Datenarten, Empfänger, Drittländer und Speicherfristen einzeln zu ergänzen.</p></section>
    <section><h2>9. Speicherdauer</h2><p>Wir speichern Daten nur so lange, wie es für den jeweiligen Zweck erforderlich ist. Handels- und steuerrechtliche Unterlagen werden entsprechend den anwendbaren gesetzlichen Aufbewahrungsfristen aufbewahrt; Anfragen ohne Vertragsbezug werden regelmäßig gelöscht, sobald sie erledigt sind und keine Ansprüche mehr zu erwarten sind.</p></section>
    <section><h2>10. Betroffenenrechte</h2><p>Betroffene haben nach Maßgabe der DSGVO insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie auf Widerruf erteilter Einwilligungen. Beschwerden können an eine zuständige Datenschutzaufsichtsbehörde gerichtet werden.</p></section>
    <section><h2>11. Pflicht zur Bereitstellung</h2><p>Ohne für Bestellung, Bezahlung und Lieferung erforderliche Daten kann kein Vertrag durchgeführt werden. Optionale Einwilligungen sind freiwillig und keine Voraussetzung für einen Kauf.</p></section>
    <section><h2>12. Aktualisierung</h2><p>Diese Erklärung ist anzupassen, sobald Anbieter, Apps, Tracking, Zahlungsarten, Märkte oder Datenflüsse geändert werden.</p></section>
  </LegalShell>;
}
