import type { Metadata } from "next";
import Link from "next/link";
import { LegalShell } from "@/components/legal-shell";
import { storeConfig } from "@/lib/config";

export const metadata: Metadata = { title: "Widerrufsbelehrung" };
export default function WithdrawalPage() {
  const m = storeConfig.merchant;
  return <LegalShell eyebrow="Verbraucherrecht" title="Widerruf" intro="Widerrufsbelehrung für Waren und nicht auf körperlichen Datenträgern bereitgestellte digitale Inhalte.">
    <section><h2>Widerrufsrecht</h2><p>Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.</p><p>Bei Kaufverträgen über Waren beträgt die Widerrufsfrist vierzehn Tage ab dem Tag, an dem Sie oder ein von Ihnen benannter Dritter, der nicht Beförderer ist, die Waren in Besitz genommen haben. Bei mehreren getrennt gelieferten Waren, Teilsendungen oder Stücken beginnt die Frist mit Erhalt der letzten Ware, Teilsendung oder des letzten Stücks.</p><p>Bei Verträgen über nicht auf einem körperlichen Datenträger befindliche digitale Inhalte beträgt die Widerrufsfrist vierzehn Tage ab Vertragsschluss.</p></section>
    <section><h2>Ausübung des Widerrufs</h2><p>Um Ihr Widerrufsrecht auszuüben, müssen Sie uns — {m.name}, {m.street}, {m.postcode} {m.city}, E-Mail <a href={`mailto:${m.email}`}>{m.email}</a>, Telefon {m.phone} — mittels einer eindeutigen Erklärung über Ihren Entschluss informieren. Sie können dafür das Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.</p><p>Sie können den Widerruf außerdem über unsere ständig erreichbare Funktion <Link href="/vertrag-widerrufen">„Vertrag widerrufen“</Link> elektronisch übermitteln. Wir bestätigen den Eingang unverzüglich auf einem dauerhaften Datenträger.</p></section>
    <section><h2>Folgen des Widerrufs</h2><p>Wenn Sie diesen Vertrag widerrufen, erstatten wir alle erhaltenen Zahlungen einschließlich der Kosten der günstigsten angebotenen Standardlieferung unverzüglich und spätestens binnen vierzehn Tagen ab Eingang des Widerrufs. Für die Rückzahlung verwenden wir dasselbe Zahlungsmittel, sofern nichts anderes ausdrücklich vereinbart wurde und dadurch keine Kosten entstehen.</p><p>Bei Waren können wir die Rückzahlung verweigern, bis wir die Waren zurückerhalten haben oder Sie den Nachweis der Rücksendung erbracht haben. Sie müssen die Waren unverzüglich und spätestens binnen vierzehn Tagen zurücksenden. Sie tragen die unmittelbaren Kosten der Rücksendung. Für einen Wertverlust müssen Sie nur aufkommen, wenn dieser auf einen zur Prüfung nicht notwendigen Umgang zurückzuführen ist.</p></section>
    <section><h2>Erlöschen bei digitalen Inhalten</h2><p>Das Widerrufsrecht erlischt bei einem kostenpflichtigen Vertrag über nicht auf einem körperlichen Datenträger befindliche digitale Inhalte, wenn wir mit der Vertragserfüllung begonnen haben, nachdem Sie ausdrücklich zugestimmt haben, dass wir vor Ablauf der Widerrufsfrist beginnen, Sie Ihre Kenntnis vom Erlöschen des Widerrufsrechts bestätigt haben und wir Ihnen eine Vertragsbestätigung zur Verfügung gestellt haben.</p></section>
    <section><h2>Muster-Widerrufsformular</h2><div className="form-template"><p>An: {m.name}, {m.street}, {m.postcode} {m.city}, {m.email}</p><p>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*) / die Bereitstellung der folgenden digitalen Inhalte (*):</p><p>Bestellt am (*) / erhalten am (*):</p><p>Name des/der Verbraucher(s):</p><p>Anschrift des/der Verbraucher(s):</p><p>Datum, Unterschrift (nur bei Mitteilung auf Papier)</p><p>(*) Unzutreffendes streichen.</p></div></section>
  </LegalShell>;
}
