import type { Metadata } from "next";
import { LegalShell } from "@/components/legal-shell";
import { storeConfig } from "@/lib/config";

export const metadata: Metadata = { title: "Allgemeine Geschäftsbedingungen" };
export default function TermsPage() {
  const m = storeConfig.merchant;
  return <LegalShell eyebrow="Vertragsgrundlage" title="AGB" intro="Musterbedingungen für Waren und digitale Produkte im B2C-Shop.">
    <section><h2>1. Geltungsbereich und Anbieter</h2><p>Diese Allgemeinen Geschäftsbedingungen gelten für Verträge zwischen {m.name}, {m.street}, {m.postcode} {m.city} (nachfolgend „Anbieter“) und Verbrauchern sowie Unternehmern über diesen Online-Shop. Abweichende Bedingungen eines Kunden gelten nur bei ausdrücklicher Zustimmung.</p></section>
    <section><h2>2. Vertragsschluss</h2><p>Produktdarstellungen sind eine Einladung zur Abgabe einer Bestellung. Im Shopify Checkout kann der Kunde Eingaben prüfen und berichtigen. Mit Betätigung der eindeutig als zahlungspflichtig gekennzeichneten Bestellschaltfläche gibt er ein verbindliches Angebot ab. Der Zugang wird unverzüglich elektronisch bestätigt. Ob bereits diese Bestätigung oder eine gesonderte Annahme den Vertrag schließt, muss mit dem tatsächlichen Shopify-E-Mail-Ablauf einheitlich festgelegt werden.</p></section>
    <section><h2>3. Preise und Versandkosten</h2><p>Alle gegenüber Verbrauchern angezeigten Gesamtpreise enthalten die gesetzliche Umsatzsteuer und sonstige Preisbestandteile. Zusätzliche Versandkosten werden am Produkt, auf der Versandseite und vor Abgabe der Bestellung angezeigt. Bei Waren nach Gewicht, Volumen, Länge oder Fläche ist der Grundpreis auszuweisen. Bei beworbenen Preisermäßigungen für Waren ist der niedrigste Preis der letzten 30 Tage anzugeben.</p></section>
    <section><h2>4. Zahlung</h2><p>Es gelten die im Checkout konkret angebotenen Zahlungsarten und Bedingungen. Eine Belastung erfolgt nach den dort angezeigten Bedingungen des gewählten Zahlungsdienstleisters.</p></section>
    <section><h2>5. Lieferung physischer Waren</h2><p>Liefergebiet, Lieferzeit und Kosten ergeben sich aus der Produktseite und „Versand & Zahlung“. Teillieferungen erfolgen nur, soweit zumutbar. Bei Verbrauchern geht die Transportgefahr grundsätzlich erst mit Übergabe an den Verbraucher oder einen von ihm bestimmten Empfänger über.</p></section>
    <section><h2>6. Digitale Inhalte und Software</h2><p>Digitale Inhalte werden in dem auf der Produktseite beschriebenen Format, Umfang und Bereitstellungsweg geliefert. Funktionalität, Kompatibilität, Interoperabilität, technische Schutzmaßnahmen, Systemanforderungen sowie Update-Zeitraum werden produktbezogen angegeben. Zugangsdaten und Download-Links dürfen nicht unberechtigt weitergegeben werden.</p></section>
    <section><h2>7. Nutzungsrechte</h2><p>Der Kunde erhält erst nach vollständiger Zahlung die auf der Produktseite beschriebene, nicht ausschließliche Lizenz. Soweit dort nichts anderes steht, sind Vervielfältigung zur Sicherung und bestimmungsgemäße Nutzung erlaubt; isolierter Weiterverkauf, Unterlizenzierung, öffentliche Bereitstellung oder Entfernung von Rechtehinweisen sind ausgeschlossen. Zwingende gesetzliche Rechte bleiben unberührt.</p></section>
    <section><h2>8. Updates digitaler Produkte</h2><p>Erforderliche Aktualisierungen werden im gesetzlich geschuldeten Zeitraum bereitgestellt und angekündigt. Optionale Funktionsupdates richten sich nach der Produktbeschreibung. Der Kunde ist gehalten, bereitgestellte sicherheitsrelevante Updates zeitnah zu installieren.</p></section>
    <section><h2>9. Eigentumsvorbehalt</h2><p>Physische Waren bleiben bis zur vollständigen Zahlung Eigentum des Anbieters.</p></section>
    <section><h2>10. Mängelrechte</h2><p>Es gelten die gesetzlichen Mängelrechte für Waren und digitale Produkte. Gegenüber Verbrauchern werden diese Rechte durch Garantien oder freiwillige Leistungen nicht eingeschränkt.</p></section>
    <section><h2>11. Haftung</h2><p>Der Anbieter haftet unbeschränkt bei Vorsatz, grober Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit, nach dem Produkthaftungsgesetz und bei übernommenen Garantien. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung auf den vorhersehbaren, typischen Schaden begrenzt. Zwingende Verbraucherrechte bleiben unberührt.</p></section>
    <section><h2>12. Widerruf</h2><p>Verbrauchern steht das gesetzliche Widerrufsrecht nach der gesonderten Widerrufsbelehrung zu. Bei sofort bereitgestellten digitalen Inhalten kann es nach ausdrücklicher Zustimmung und Kenntnisbestätigung mit Beginn der Vertragserfüllung erlöschen.</p></section>
    <section><h2>13. Streitbeilegung</h2><p>Der Anbieter ist nicht bereit und nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen, soweit keine abweichende gesetzliche Pflicht oder tatsächliche Teilnahme besteht.</p></section>
    <section><h2>14. Schlussbestimmungen</h2><p>Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts. Bei Verbrauchern gilt diese Rechtswahl nur, soweit zwingender Schutz des Staates des gewöhnlichen Aufenthalts nicht entzogen wird. Gerichtsstandsvereinbarungen gelten nur im gesetzlich zulässigen Umfang.</p></section>
  </LegalShell>;
}
